sksamuel/avro4s

avro4s-json/src/main/scala/com/sksamuel/avro4s/json/JsonToAvroConverter.scala
avro4s-json/src/test/resources/avro1_with_strings.avsc
avro4s-json/src/test/resources/avro2_with_strings.avsc
avro4s-json/src/test/scala/com/sksamuel/avro4s/json/JsonToAvroConverterTest.scala

Allowing the user to specify if the schema generated should specify use String not Utf8. This way when Avro deserialises the payload will create String instances not Utf8
Not sure what the best way is to change the macro ToSchema to allow a flag. I leave that to your capable hands :)

Schema specifies use String not utf8

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroInputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroOutputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroBinaryOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroDataOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroInputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala

issue #21 
- removed the flag "include schema" from the AvroOutputStream because according with the Apache Avro documentation the schema is always included with the Data. So it's not need it.
[http://avro.apache.org/docs/1.8.0/gettingstartedjava.html: "Data in Avro is always stored with its corresponding schema, meaning we can always read a serialized item regardless of whether we know the schema ahead of time."
- added "AvroBinaryInputStream" and "AvroDataInputStream" that extends AvroInputStream, in order to distinguish between data file stream or binary stream
- fixed the Unit tests

Fixed avro binary serialization/deserialization 

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Fixed macro outside avro4s package by using fully qualified name for SchemaFor in ToRecord macro.

Fixed macro outside avro4s package

---

avro4s-generator/src/main/scala/com/sksamuel/avro4s/TemplateGenerator.scala
avro4s-generator/src/test/scala/com/sksamuel/avro4s/TemplateGeneratorTest.scala

The java enum template generator wasn't including the semicolon :)

fixed missing semicolon in enum template generator

---

avro4s-core/src/test/resources/optiondefaultvalues.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

A filed option with default value to none generate a scheam with "default : "None". Example :
`case class OptionDefaultValues(
name: String = "sammy",
description: Option[String] = None,
currency: Option[String] = Some("$")
)`
produce this schema :
`{"type":"record","name":"OptionDefaultValues","namespace":"com.sksamuel.avro4s","fields":[{"name":"name","type":"string","default":"sammy"},{"name":"description","type":["null","string"],"default":"None"},{"name":"currency","type":["null","string"],"default":"Some($)"}]}`
With this fix the schema is 
`{
"type": "record",
"name": "OptionDefaultValues",
"namespace": "com.sksamuel.avro4s",
"fields": [
{ "name": "name", "type": "string", "default": "sammy" },
{
"name": "description",
"type": ["null", "string"]
},
{
"name": "currency",
"type": …

Fix problem with option default value

---

avro4s-generator/src/main/scala/com/sksamuel/avro4s/ModuleGenerator.scala
avro4s-generator/src/main/scala/com/sksamuel/avro4s/TemplateGenerator.scala
avro4s-generator/src/test/scala/com/sksamuel/avro4s/FileRendererTest.scala
avro4s-generator/src/test/scala/com/sksamuel/avro4s/TemplateGeneratorTest.scala

Hey! Quick little bugfix here, you were generating `domain/scala` files when using `sbt-avro4s`.

Template filename bug

---

avro4s-core/src/test/resources/mutrec.avsc
avro4s-core/src/test/resources/recursive.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Handle recursive schemas by splitting up the record's schema before fields are added, and the record's schema after fields are added, as separate values.

Recursive schemas

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroDataTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

My apologies; I should've tested `toRecord` and `fromRecord` as well! 
Right now there appears to be an issue where if you're using a recursive schema, you can't rely on the `SchemaFor[T]` being implicitly built; you have to provide a `implicit val schema = SchemaFor[T]` line so that the compiler doesn't go into recursive loops. I'm tentatively okay with that; what do you think?

targeted laziness in to/fromRecord

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/TraitObjectEnumerationExample.scala

Represent the following structure as Int
```
sealed trait Base
case object A extends Base
case object B extends Base
```

example using custom types to map sealed trait+case object enum

---

README.md
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

TODOs:
* `ScaleAndPrecision` should go somewhere else. It is a big project; so, please guide me.
* Should the example print the schema of `MyDecimal`?
Ideally, it would be nice for users to have the ability to use different `ScaleAndPrecision`s within schema `BigDecimal`s. I'm not sure how to do that yet but would love to do this if it is possible.

set BigDecimal scale and precision for schema

---

README.md
avro4s-core/src/test/resources/optionalunion.avsc
avro4s-core/src/test/resources/union.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroInputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-generator/src/main/scala/com/sksamuel/avro4s/ModuleGenerator.scala
avro4s-generator/src/test/scala/com/sksamuel/avro4s/ModuleRendererTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Support for general union types! 
I did my best to make sure existing usecases were unimpacted; `avro4s` still uses Options and Eithers for the simpler cases, but now it can support larger unions as well.

Coproducts!

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala

The evaluation of the typeVals on every invocation of FromValue.safeFrom is causing a huge performance impact under load due to excessive reflection calls.
Changing typeVals to a lazy val means it is only evaluated if we are matching a GenericData.Record.
Through profiling of our application under load this change has resulted in a noticable improvement in performance.
Here is an example stack trace identified as consuming a majority of CPU: 
rules-akka.actor.default-dispatcher-31 [RUNNABLE]
scala.reflect.internal.Types$Type.members() Types.scala:260
com.sksamuel.avro4s.FromValue$.com$sksamuel$avro4s$FromValue$$safeFrom(Object, TypeTags$WeakTypeTag, FromValue) FromRecord.scala:134
com.sksamuel.avro4s.FromValue$$anon$10.apply(Object, Schema$Field) FromRecord.scala:181 …

Optimise reflection evaluation

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroInputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/ReadmeTest.scala
avro4s-json/src/main/scala/com/sksamuel/avro4s/json/JsonToAvroConverter.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
project/Build.scala

This PR removes all compiler warnings and requires going forward that no more warnings are allowed by adding `-Xfatal-warnings` to the build's `scalacOptions`.
This PR was motivated by #76, though it does not fix the bug. I am trying to reproduce #76 via a unit test but so far have not been able to. However, please consider merging these small changes to prevent compiler warnings being introduced in the future.

Remove all compiler warnings

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

this should avoid recreating the schema with every call to SchemaFor#apply
ToRecord macro should benefit from this since we don't have to push SchemaFor at least for now. 
I am going to make another PR for the implicit SchemaFor

caching the schema for perf reasons

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/FixedTypeTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Associated PR: https://github.com/sksamuel/sbt-avro4s/pull/9
Added proper support for `fixed` types, currently represented as:
`@AvroFixed(32) case class SHA256(bytes: WrappedArray.ofByte) extends AnyVal`

proper fixed type support

---

README.md

scala.Enumeration is not supported by avro4s, this is an update to let all users know.

Removed support for scala.Enumeration

---

avro4s-core/src/test/resources/nested_in_uppercase_pkg.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/FixedTypeTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/RecordFormatTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/UppercasePkg/Data.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Real package path in generated schema retrieved in generated schema instead of lowercase heuristics. It addresses #100 by unifying method of determining package name of a type both in `FromValue` typeclass derivation for coproducts and generation of schema in `SchemaFor` macro.

Real package path in generated schema

---

README.md
avro4s-core/src/test/resources/sealed_traits.avsc
avro4s-core/src/test/resources/trait_subtypes_duplicate_fields.avsc
avro4s-core/src/test/resources/trait_subtypes_duplicate_fields_same_type.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/RecordFormatTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/TraitObjectEnumerationExample.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Instead of custom encoding for sealed traits, introduced encoding as unions using shapeless.Generic. Kept optimal, string-based encoding in case when all sealed hierarchy descendants are singleton objects.
@sksamuel I know this is breaking change, but brings nice support for end-to-end sealed hierarchies. Please tell what do you think.

Introduced consistent end-to-end, union-based encoding of sealed traits

---

README.md
avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/TraitObjectEnumerationExample.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Following discussion in #102, replaced string-based encoding for sealed trait + only case object descendants with enum-based one.

Sealed trait + case object encoded as enum

---

avro4s-core/src/test/resources/namespace.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/annotations.scala

For record types, it is essential to be able to modify namespaces of records, especially if you're avro is meant to be read by multiple languages on different platforms.
This pull request adds the ability to annotate a case class with @AvroNamespace to modify the generated namespace name in the schema.
For example:
```scala
package com.github.yuval
@AvroNamespace("com.yuval") case class Foo(s: String)
```
Will generate:
```json
{
"type": "record",
"name": "Foo",
"namespace": "com.yuval",
"fields": [
{
"name": "s",
"type": "string"
}
]
}
```

Add support for modifying namespace in record types

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/RecordFormatTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/TypeHelper.scala

When one of the `FromValue` implicits for primitive types parses the actual type of the value, it first allocates a string and then converts to the primitive type:
For example:
```scala
implicit object IntFromValue extends FromValue[Int] {
override def apply(value: Any, field: Field): Int = value.toString.toInt
}
```
Under heavy load, this generates a decent amount of garbage strings. As an example, here is a sample from a profile I ran on code which consumes ~ 500,000 avro records:
We generate nearly 1GB of strings for parsing out `Int`s.
Since [`safeFrom`](https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala#L143) matches type parameters via `WeakTypeTag`, we can safely cast to the underlying primitive type without needs to …

Avoid unnecessary string allocations in `FromValue` implicits

---

README.md
avro4s-core/src/test/resources/localdate.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroInputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Hello there,
I thought it may be useful to have support for the java LocalDate inside avro4s.
It may be a good idea to start grouping similar types in a coherent modules `TimeInstances` ? I was looking how circe handled that: 
https://github.com/circe/circe/blob/master/modules/java8/src/main/scala/io/circe/java8/time/TimeInstances.scala
Also another idea to consider would be to have the definition for all the implicits SchemaFor/FromValue/ToValue for a given type in one place rather than having them split in different files by implicit type as it's done now.
Thanks.

Add support for java LocalDate type

---

README.md
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Fixes #125 
This fixes a major pain to adoption for anyone whos project contains flags to mark unused vals as errors.
Also one small documentation link that would have saved me some time.

Fix unused val warning in generated code

---

avro4s-core/src/test/resources/optionscalaenum.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/UniverseTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Fixes issue #135 
My knowledge of the reflection api is limited, so the solution may not be optimal.
Also note there may be similar cases, where some types `T` are not supported within an Option[T].

Fix for issue #135: NPE on Option[Enumeration]

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

When trying to create a schema for a `union` type like:
```avro
record test {
union { null, decimal(9,2) } dec = 222.22;
}
```
```scala
case class Test(opt: Option[BigDecimal] = Some(1234.56))
```
The following exception happens:
```
[info] [info] A case class with `logicalType` fields and default values from .avdl should
[info] [error]   ! deserialize correctly
[info] [error]    org.apache.avro.AvroRuntimeException: Unknown datum class: class scala.math.BigDecimal (JacksonUtils.java:87)
[info] [error] org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
[info] [error] org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
[info] [error] org.apache.avro.Schema$Field.<init>(Schema.java:423)
[info] [error] …
```

Fix how option default value are handle

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala

I made FromValue serializable which enables you to give FromRecord as a context bound but still have a serializable class.
As an example see this gist to use it with Apache Flink (and a KafkaConsumer/Producer):
https://gist.github.com/wzorgdrager/c27805ae9d627b57e736fe09dd09aad9

Making FromValue serializable (and therefore FromRecord).

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

The current accessor fails when the default value sits within a companion object. Atm this is just an issue on my master, as the avro4s master does not support ADTs with `object`-namespacing at all. But I want to keep sync as far as possible.

Fixed broken default value accessor

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Sorry. I can only speak English a little.
I use avro4s last version (1.8.3)
GenericRequestor writing  NullPointerException.
Cause was that the schema was null.
https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L179
I tried change to refer SchemaFor#genTraitObjectEnum method.
https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala#L205-L220
``` 
java.lang.NullPointerException: null of union in field category of example.app
at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:145)
at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:139)
at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75) …
```

support optional enums

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/SealedTraitEncoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/SealedTraitSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

I noticed that `@AvroName` is not respected in enum branches for `case object` style enums. I've added a few test cases and got them passing but I don't know if the solution I've come up with is the best one. Please let me know if there are changes I should make.

Respect avroname in sealed case object enums

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/UUIDDecoderTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/Decoder.scala

Another small PR. Noticed that there's no branch to handle `Utf8` when decoding `UUID`s so added a test and implementation.

Decode UUIDs from org.apache.avro.utl.Utf8

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/AvroNameEncoderTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/NameResolution.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Respect AvroName when generating and encoding enum symbols for sealed trait case object hierarchies

Respect AvroName when generating and encoding enum symbols 

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaHelper.scala

Some changes to improve encoder performance. This gives a 10 to 30 percent speedup in my benchmark cases. I suspect larger schemas will see a bigger improvement.
Reuse generated field encoders in the record macro (same way as the decoder performance pr i made)
Microoptimized SchemaHelper.extractTraitSubschema. This is called for each encoded field and popped out in yourkit. The code is not very idomatic scala anymore.
Benchmark results:
```
2.0.3:
[info] Benchmark                                                  Mode  Cnt     Score    Error   Units
[info] EncodeBench.measureEncodeCaseClass                        thrpt    5  2015.377 ±  5.290  ops/ms
[info] EncodeBench.measureEncodeCaseClassWithCaseClassCoproduct  thrpt    5  1769.699 ± 15.953  ops/ms
[info] …
```

Improve encode performance

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/TupleEncoderTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/TupleEncoders.scala

Tuple encoders pass common tuple schema to tuple members encoders, it's
ok when members are primitive types because their encoders don't use
schema to encode value, String fallbacks to Utf8. For example if we use
Option as member of tuple it requires UNION schema to encode but gets RECORD.
To fix this every member of tuple should take only it's part of schema.

Fix tuple encoders

---

README.md

This fixes a couple of errors in the schema given as the output of the `@AvroDoc` example in the readme.

Fix the output of the AvroDoc example in the readme.

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/EitherSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

```
AvroSchema[Either[String, Option[Int]]]
org.apache.avro.AvroRuntimeException: Nested union: ["string",["null","int"]]
at org.apache.avro.Schema$UnionSchema.<init>(Schema.java:849)
at org.apache.avro.Schema.createUnion(Schema.java:189)
at org.apache.avro.Schema.createUnion(Schema.java:194)
at com.sksamuel.avro4s.SchemaFor$$anon$5.schema(SchemaFor.scala:92)
at com.sksamuel.avro4s.AvroSchema$.apply(AvroSchema.scala:21)
```

Fix SchemaFor when either have nested union types

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroSchemaMerge.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroSchemaMergeTest.scala

This PR should fix this issue: https://github.com/sksamuel/avro4s/issues/303
Also, i tried to fix this: in some cases if there is no default value, null schema was last in union, but as avro specification says it is better to put null schema as first schema in union (https://avro.apache.org/docs/1.8.2/spec.html#Unions).

Issue 303 - Fix AvroMergeSchema

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/OptionDecoderTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/Decoder.scala

I want to be able read fields that declared as non-optional in Avro schema utilizing `optionDecoder`.
This is common case in my project when I migrate older model to the new one where certain fields become optional.
With this change I could read "legacy" records into the new schema where certain fields are now optional.
The problem with existing implementation is that in such case it throws AvroRuntimeException with "Not a union: " message.

Use optional decoder to read non optional fields

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaHelper.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/CoproductEncoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala

I noticed that for some reason the test for default arrays and maps had been omitted. I was running into issues generating schemas with these kind of default values so I've had  a stab at implementing the feature here.
For some reason this broke the `CoproductEncoderTest`. I couldn't figure out exactly what the problem was but making the type name  check slightly more flexible in `SchemaHelper` fixed the test.

Add default values for seqs and maps

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-core/src/test/resources/default_values_optional_union.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala

I ran into a problem where setting the default value of an `Option` field caused an error. This was because of the way the current behaviour which allows a default value of `null` to generate a union schema was implemented.
I've fixed the behaviour so that setting a default value of `None` renders a `null` in the schema. However, this might not be a complete implementation because I can see an argument that if the default value is set to `None` then reading an older record (i.e one written before the field existed and hence requiring the default value) should return `None`, and I _think_ that at the moment it would read `null`.

Optional unions with default values set to None

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaHelper.scala
avro4s-core/src/test/resources/optional_default_values.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala

This is another part of defaults for `map` and `array` types that I missed. Specifically, in cases where the default is a map or array it wasn't moving the default value to the head of the type list in the union.

Optional unions

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/ArrayDecoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/ArrayEncoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/ArraySchemaTest.scala
project/Build.scala

Probably first needs a review
* For schema generation any `Iterable` is now accepted and yields `Array` in the schema
* Encoders/Decoders need some more explicit handling becuase the low priority implicit is a bit less performant
I have also seen that Scala 2.13 fails because of missing Magnolia dependency.
Might need some more updates for 2.13 because of the collections changes
https://github.com/scala/scala-collection-compat
Got some inspiration here:
https://github.com/playframework/play-json/blob/dd7c7d1d9c9f329829809bd13e0dccd058f30c1c/play-json/shared/src/main/scala/play/api/libs/json/Writes.scala#L395
https://github.com/playframework/play-json/blob/dd7c7d1d9c9f329829809bd13e0dccd058f30c1c/play-json/shared/src/main/scala/play/api/libs/json/Reads.scala#L229

fix #339 adds support for immutable Seq and more

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/SealedTraitDecoderTest.scala

Ran into an issue where enums with the `@AvroName` annotation were failing to decode. For some reason it seems to only be replicated by a round trip through the encoder and decoder. I've attached a test which reproduces the issue but it may be in the wrong place. (given that it's in the `decoder` test folder).

Fix incorrect name lookup with enums

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaHelper.scala
avro4s-core/src/test/resources/case_class_default_values.json
avro4s-core/src/test/resources/case_object_default_values.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/Blah.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueRecordTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala
build.sbt

- allows union defaults to be user defined case classes / case objects
- handles correctly reordering the schema as per the spec
- case class defaults are json objects
- case object defaults are empty json object

Issue #352 - User defined classes can't be used as defaults in a Union

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/TupleDecoderTest.scala

Otherwise decoding fails with `org.apache.avro.AvroRuntimeException: Not an array`. I guess this would also fix decoding of tuples that contain other complex types.

Correctly decode tuples that contain a Seq

---

avro4s-core/src/test/resources/avro_sort_priority_union_with_default.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroSortPrioritySchemaTest.scala

Tests that the @AvroSortPriority annotation, does not break the reordering of the schema fields that happens when we add a default union value
Also fixes a small typo in test class naming

Small PR to add a test around sort priority and defaults

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/github/Github202.scala

This is a fix for the test in github-202
There is no issue with Avro4s, just some weirdness with how aliases work in Avro
If you add an alias to a single field, you need to alias all fields and alias on the record level too
I've added a pure java api version of the test too, as i think it makes the solution very explicit :)

fixes broken test for issue 202

---

.travis.yml
avro4s-core/src/main/scala/com/sksamuel/avro4s/annotations.scala
project/Build.scala
snapshot_deploy.sh

I think it's a bit more standard (and more parallel) to put the matrix of Scala versions in `.travis.yml`, rather than using `+test` and `+publish`. it's nice to see at a glance in the Travis-CI results which versions are failing
btw it seems a bit suspicious to me that you have two JDKs in the Travis-CI matrix but you run `snapshot_deploy.sh` from both, aren't you double-publishing snapshots? I didn't check or change this
was it intentional that you weren't building/testing on JDK 8, only 10 and 11? I changed it to 8 and 11, but perhaps that's wrong

bump Scala versions, modernize Travis-CI config

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroDataOutputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/streams/output/AvroDataOutputStreamCodecTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/streams/output/BasicOutputStreamTest.scala

There's an issue with writing raw `GenericRecord` using `AvroDataOutputStream` caused by cast to `ImmutableRecord`.
The proposed solution just narrows the type of encoded entity to `GenericRecord`, since that's the most generic type required by `GenericDatumWriter[GenericRecord]`.

Fixed encoding GenericRecord using AvroDataOutputStream

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/FromRecordTest.scala

I think `FromRecord` should be decoding using the reader schema (for the class being decoded to) rather than the schema of the record being decoded. Currently with more than basic classes, `T` needs the same fields as the writer.
Sorry, if this is wrong but I think it makes sense unless I've misunderstood what `FromRecord` is supposed to be used for?
The test seemed to fit in with the decoding tests but let me know if there is a better place for it.

FromRecord should decode using reader schema

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-core/src/test/resources/github/github_389.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue389.scala

Added support for OffsetDateTime objects. Created a custom logical type 'datetime-with-offset' that is backed by string. OffsetDateTimes are encoded by converting them to a String using the DateTimeFormatter.ISO_OFFSET_DATE_TIME . Example Avro schema can be found in test/resources/github/github_389.json.

ISSUE-389 | Add support for OffsetDateTime

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-core/src/test/resources/localdatetime.json
avro4s-core/src/test/resources/localtime.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue387.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/DateDecoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/DateEncoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DateSchemaTest.scala

~~Fixed the Encoder for LocalTime objects to properly convert from nanoseconds to millisseconds. Nano second values are truncated to the millisecond precision. LocalTime.now() produces millisecond precision values by default so the schema and encoder/decoder are inline with default functionality of the LocalTime object even though LocalTime does allow for a higher level of precision.~~
In Java8 the default functionality of LocalTime.now() produces millisecond precision, however, in Java11 it produces microsecond precision.  I change the logical type of LocalTime to be `time-micros` and updated the encoder and tests accordingly.

ISSUE-387 | Fixed LocalTime Encoder to properly convert to milliseconds

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/CustomDefaults.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/Github411.scala

if a default value is a case class with default values, they were not
correctly handled.
Use the default resolver back to resolve the default value in the
default value recursively
Known issue: at some point, we need the type name if the schema is a
union. The name used here does't resolve the correct name if an
@AvroName annotation is used on the class. Same applies on the field
name, no FieldMapper is applied.
Also, in `CustomUnionDefault` some code left me a bit puzzled, so I changed it to what seemed the right thing
```scala
CustomUnionDefault(trimmedClassName(p), parse(write(p)).extract[Map[String, Any]].mapValues {
case (name, b: BigInt) if b.isValidInt => b.intValue: Any
case (name, b: BigInt) if b.isValidLong => b.longValue: Any
}
```
changed to:
```scala …
```

recursively resolve default values

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

This also solves the issue that `SchemaFor` is not serializable since `Schema` is instantiated eagerly and therefore needs to be serializable.

Use SAM type to instantiate default SchemaFor

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroBinaryInputStream.scala

Improve AvroBinaryInputStream by using GenericDatumReader constructor with GenericData singleton instead of creating new instances of GenericData.
https://github.com/apache/avro/blob/4cd778a7e0de048eacf2a06abe3d0e310bbcc343/lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java#L61

Improve AvroBinaryInputStream by using GenericData singleton

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaHelper.scala

NameExtractors are expensive to build; this pre-computes the
names and fullnames needed outside of encoding / decoding.
Also, SchemaHelper.extractTraitSubschema compiles the same regex on each
call, this is now extracted.
Also, removed unused code.
Benchmark results:
```
::Benchmark avro4s union type with type param encoding:: 0.005265 ms
::Benchmark avro4s union type with type param decoding:: 0.00267 ms
```
Encoding speedup is x 2.6, decoding speedup is x 4.8.
Flame graphs.
Encoding before:
Encoding after:
Decoding before:
Decoding after:

Improve encoding / decoding performance

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/test/resources/coproduct_with_default.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/CoproductSchemaTest.scala

Support for schema generation for fields with shapeless Coproduct type and default value.
Note that we only support `Inl(...)`, not `Inr(...(Inl(...)))`, because "the type of the default value must match the first element of the union" (quoted from the [Avro spec](https://avro.apache.org/docs/current/spec.html#Unions)).
Without the `Inl(x)` case added to `DefaultResolver`, the pattern match falls into the `Product` case and the test fails with:
```
org.apache.avro.AvroTypeException: Invalid default for field u: {"head":123} not a ["int","string","boolean",{"type":"record","name":"Gimble","namespace":"com.sksamuel.avro4s.schema","fields":[{"name":"x","type":"string"}]}]
```

Support shapeless coproduct fields with default values

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeInfo.scala

Thanks for the great library! As before, I discovered another bug related to decoding sealed traits/enums in combination with the Play classloader. I changed every reference to getClass.getClassLoader I could find to Thread.currentThread().getContextClassLoader.

fix classloader for decoding in combination with play dev

---

README.md
avro4s-kafka/src/main/scala/com/sksamuel/avro4s/kafka/GenericSerde.scala
avro4s-kafka/src/test/scala/com/sksamuel/avro4s/kafka/GenericSerdeTest.scala

As discussed in https://github.com/sksamuel/avro4s/issues/447
This MR adds support for Json and Data Avro format in the Kafka `GenericSerde` class and documents its usage `readme.md`. By default, the behaviour is the same as before, i.e usage of `BinaryFormat`.
Behaviour is validated with a few supplementary UT, and I did a quick manual validation with Akka Streams (https://github.com/sv3ndk/kafka-to-rdbms-export-akka-demo/blob/master/src/main/scala/com/svend/demo/DataGenerator.scala#L27).

Generic serdes

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/SafeFrom.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/CoproductDecoderTest.scala

This feels dirty, but adding a special case for `Coproduct` in `SafeFrom` fixes decoders for nested coproducts.
Maybe we should put this in the `:+:` decoder?

Fix nested coproducts

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/SafeFrom.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/CoproductDecoderTest.scala

After upgrading to the latest `mu-scala` release, we also are using avro4s 3.x.
I had some problems with decoding some union types where one of the elements is an array.
It seems we currently are attempting to decode the elements of the union with specific decoders but still with the schema of the complete union.
Here I unfold the schemas for union types and filter to the schemas that make sense for the `SafeFrom` instance that we are building. Then we try them one by one until one of them succeeds, otherwise we throw an error which includes the error messages of all the schemas we have tried.
Today was the first time looking under the cover of `avro4s` so I am not sure if these changes are within the right spirit? I can probably try to clean this up a bit if we think the solution looks …

Fix decoder for coproducts with arrays/maps

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue432.scala

Encoders should be serializable, denote the value Avro: DecimalConversion with transient lazy to allow it.

ISSUE-432 | Fix serializable Encoder[BigDecimal] (#432)

---

project/Build.scala

Hi,
I recently noticed that when you use avro4s, you end up with scala-compiler on the run-time classpath. But it's needed only at compile-time, and including it in the run-time classpath adds unnecessary bloat for the users.

don't pull in scala-compiler as run-time dependency

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Records.scala
avro4s-core/src/test/resources/doc_field_regular_case_class.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroDocSchemaTest.scala

In order to avoid duplicating the doc field, check whether the current class is a value class before extracting the annotation from it.
Fixes #509

Check whether class is value class

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroBinaryInputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroDataInputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroDataOutputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroJsonInputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultAvroOutputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

This is the easiest way to avoid the performance hit discussed [here](https://github.com/sksamuel/avro4s/issues/495#issuecomment-659492364) 
we can fall back to use the ad-hoc instance of the resolvable encoder / decoder, which is a lazy val and has some slight performance hit, but by this it becomes impossible to accidentally perform resolution multiple times.
I haven't had time to create benchmarks yet to check how much of a win it would be to explicitly resolve at the right place, I will investigate in the next couple days. I expect the win to be very small, if noticeable at all, to be honest.

Use ad-hoc instances so that expensive resolving isn't performed on stream creation time

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeGuardedDecoding.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/CoproductDecoderTest.scala

Needs to consider all variants of byte array for in coproduct type guards.
Fixes #520

Correctly decode coproduct containing byte array

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

This PR just adds a `getClass` for the `output` seen in the exception message.
I had a confusing instance where my type `T` was not being marshalled, and it wasn't clear to me that it was being seen as a `String`. Eventually we figured out that it was because our case classes extended `AnyVal`.

Add getClass String for ToRecord failure

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/CustomDefaults.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/test/resources/default_values_instant.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala

Hey 
I added `java.time.Instant` top-level default value support for class definitions like:
```scala
case class ClassWithDefaultInstant(min: Instant = Instant.MIN, max: Instant = Instant.MAX, epoch: Instant = Instant.EPOCH)
```
To support `Instant.MAX` and `Instant.MIN` I used the boxed primitive max and min value from `scala.Long` in order to avoid an `java.lang.ArithmeticException: long overflow`. 
If this is an issue I need to come up with a different solution. I also thought about using a `scala.math.BigInt` or `scala.math.BigDecimal` in combination with Avro's `"logicalType": "decimal"`, but this would break the avro4s default `java.time.Instant` to `"logicalType": "timestamp-millis"` conversion. 
Please let me know if further action on my side is required :slightly_smiling_face: …

Add support for java.time.Instant default values. Fixes #542

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeGuardedDecoding.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue545.scala

Hello!
I've added a change in the order of how internal decoders from scenarios using `Either[X, Map[_, _]]` or Shapeless coproduct (including a map in the coproduct) are being returned.
In case of having `Either[X, Map[_, _]]` it will return a decoder of type `Either[X, ArrayDecoder]` instead of `Either[X, MapDecoder]` since there is a small bug in the order how the types are being checked.

Change type guard order. Fixes #545

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/FieldMapper.scala

I would like to feel free to implement FieldMapper.
For example, implement names transformation as snake_case to CamelCase using `guava` lib or something else.

Fix FieldMapper not sealed to allow free implementation

---

avro4s-refined/src/main/scala/com/sksamuel/avro4s/refined/package.scala
avro4s-refined/src/test/scala/com/sksamuel/avro4s/refined/RefinedTest.scala

Fixes #571 
```scala
implicit def refinedSchemaFor[T, P, F[_, _]](implicit schemaFor: SchemaFor[T]): SchemaFor[F[T, P]]
```
The above signature doesn't constrain `F[_, _]` to be a refined type. So I think when trying to resolve a schema for `Map[String, String]`, this actually matches the shape of the above instance intended for a refined type `SchemaFor[F[T, P]]` where `T` is now a string - so this just uses the `SchemaFor[String]` instance and we end up with a schema typed as a string.
By saying that `F` needs a `RefType` instance, `refinedSchemaFor` now can't be used for for a `Map[_, _]` which can now correctly resolve to `mapSchemaFor`.

Constrain refinedSchemaFor to require a RefType

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/CollectionsAndContainers.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/ShapelessCoproducts.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeGuardedDecoding.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue545.scala
avro4s-refined/src/main/scala/com/sksamuel/avro4s/refined/package.scala
avro4s-refined/src/test/scala/com/sksamuel/avro4s/refined/RefinedRoundtripTest.scala
build.sbt

Hi @sksamuel 
Been trying a few things on version 4.0.0 recently and stumbled across a set of problems when combining `Refined` and shapeless' `Coproduct`. I believe the issue is clear in the tests I've added to this.
I pinpointed the problem in the `TypeGuardedDecoding` and how - for example - `implicitly[WeakTypeTag[NonEmptyString]].tpe <:< typeOf[String]` will never be true.
The solution I propose may not be ideal but I wanted to keep the spirit of what was there already.

Refined + TypeGuardedDecoding issues

---

.github/workflows/pr.yml
README.md
avro4s-core/src/main/scala/com/sksamuel/avro4s/AnnotationExtractors.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/annotations.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/Github587.scala

`AvroSortPriority` takes a `priority` to sort the elements of the union, but it is quite strange from the user perspective because the main goal is to set the elements inside the union in the order that we expect.
I have written a `@AvroUnionPosition` attribute that works in the same way but takes a `position`. It will be used like:
```scala
sealed trait Fruit
@AvroUnionPosition(0)
case object Unknown extends Fruit
@AvroUnionPosition(1)
case class Orange(size: Int) extends Fruit
@AvroUnionPosition(2)
case class Mango(size: Int) extends Fruit
```
And it will produce an union with `[Unknown, Orange, Mango]`. I think it is more clear from the user perspective.
Also when we want to ensure backward/forward compatibility this can allow us to just add new elements without touching the existing …

add AvroUnionPosition attributute to control position of elements in unions

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/Decoder.scala

Details are here https://stackoverflow.com/questions/64903163/implicit-resolution-fail-in-reflection-with-toolbox
Without this fix the following runtime-reflection code
```scala
toolBox.eval(q"""
import com.sksamuel.avro4s.Decoder
import mypackage.MyCaseClass
Decoder.applyMacro[MyCaseClass]
""")
```
throws
```none
scala.tools.reflect.ToolBoxError: reflective compilation has failed:
object error is not a member of package sys
```

Make sys.error hygienic in macro 2.0.x

---

avro4s-refined/src/main/scala/com/sksamuel/avro4s/refined/package.scala
avro4s-refined/src/test/scala/com/sksamuel/avro4s/refined/RefinedRoundtripTest.scala
avro4s-refined/src/test/scala/com/sksamuel/avro4s/refined/RefinedTest.scala

Having a Map[String Refined T, A] is quite common and the only option at the moment is to convert the keys to string. This should not be required only if the type of the key is a refined String.
This PR adds support for refined keys on Maps.

Added instances for Encoder/Decoder/SchemaFor for Maps that have refined strings as keys

---

README.md
avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeUnionEntry.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeUnions.scala
avro4s-core/src/test/resources/namespace_class_adt_field.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroNamespaceSchemaTest.scala

Thanks for your work on avro4s!
Currently, given the following code:
```scala
@AvroNamespace("com.yuval")
sealed trait TestAnnotated
final case class TestAnnotatedImpl(value: AnnotatedNested) extends TestAnnotated
@AvroNamespace("com.yuval.nested")
case class AnnotatedNested()
```
`SchemaFor[TestAnnotated]` will produce the following schema:
```json
[ {
"type" : "record",
"name" : "TestAnnotatedImpl",
"namespace" : "com.yuval",
"fields" : [ {
"name" : "value",
"type" : {
"type" : "record",
"name" : "AnnotatedNested",
"fields" : [ ]
}
} ]
} ]
```
mainly, the `namespace` field is missing from the `AnnotatedNested` record. 
Note, that `Encoder[TestAnnotated].schema` produces schema that contains `namespace` field for the `AnnotatedNested ` record:
```json
[ {
"type" : "record",
"name" : …
```

Fix "namespace" in the derivation of SchemaFor for ADTs and minor fixes in examples from the documentation

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/ValueTypes.scala
avro4s-refined/src/test/scala/com/sksamuel/avro4s/refined/RefinedTest.scala

Fix #664
Hi @sksamuel,
I'm using Avro4s with refined and I notice this bug.
The good thing with my fix here is that it solves the problem with refined but also with any value class. 🙂

Fix #664: When value classes are used as default parameter, they're not eliminated by the compiler anymore

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Records.scala

When using `avro4s` with other open-source projects relying on Avro, sometimes Avro version conflicts arise. For instance, the `4.0.x` release series of `avro4s` uses Avro 1.9.2, while Apache Spark 3.1.x uses Avro 1.8.2.
We've noticed that when using `avro4s` 4.0.x with Spark 3.1.1, sometimes the Spark job would crash with the following error (see **Test Result** below for a reproducible example):
```
java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.<init>(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;)V
at com.sksamuel.avro4s.Records$.buildSchemaField(Records.scala:236)
at com.sksamuel.avro4s.Records$.$anonfun$schema$1(Records.scala:149)
```
which is caused by this line in `avro4s-core/src/main/scala/com/sksamuel/avro4s/Records.scala`: …

Use an alternative constructor for Schema.Field for better Avro backward compatibility

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/magnolia.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/unions.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/magnolia.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/unions.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/magnolia.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/unions.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/valuetypes.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Annotations.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/DatatypeShape.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Names.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Subtypes.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/Scala3EnumDecoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/Scala3EnumEncoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/SealedTraitEncoderTest.scala
build.sbt
project/Build.scala
project/build.properties

This is a draft of how new Scala 3 enums serialization/deserialization could work. This PR needs apparently a good review, given that I'm quite fresh with Avro in general and with Avro4s particularly.
Notes: 
- Scala 3 enums are translated to/from Avro enums, not unions.
- Workaround of `@AvroName`  being attached not only to the enum sealed class, but to the inheriting case classes/objects. Probably I should look into Magnolia to figure out if it is a bug or a feature.

Magnolia upgrade to V1.0.0. Fix Enums SerDe

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/BaseTypes.scala

Fixes https://github.com/sksamuel/avro4s/issues/712

Use current thread's classloader when decoding Scala enums

---

project/Build.scala
project/build.properties

Updated json4s to v4.0.5 along with other dependencies: jmh, avro.
sbt 1.6.2
While upgrading our codebase to use json4s v4.x I found out that avro4s is a blocker since it's using v3.6.x.
This PR updates json4s and other dependencies to their latest versions

Update json4s to v4.0.5

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/unions.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/SealedTraitDecoderTest.scala

Fix for supporting decoding sealed traits of case classes. The tests were already written, I've just made them run with success.

Support decoding sealed trait of case classes

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/records.scala

currently if you try to decode a case class with  field not present in schema, you'll get you a bit useless message like this
```
[info]   java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because "field" is null
[info]   at com.sksamuel.avro4s.decoders.SchemaFieldDecoder.<init>(records.scala:64)
[info]   at com.sksamuel.avro4s.decoders.RecordDecoder.$anonfun$1(records.scala:19)
[info]   at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:932)
[info]   at scala.IArray$package$IArray$.map(IArray.scala:179)
[info]   at com.sksamuel.avro4s.decoders.RecordDecoder.decode(records.scala:20)
[info]   at com.sksamuel.avro4s.AvroDataInputStream.$init$$$anonfun$1(AvroDataInputStream.scala:40)
[info]   at scala.Option.map(Option.scala:242)
[info]   at …
```

improve error message in case of schema mismatch

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/unions.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/EnumTypes.scala
avro4s-core/src/test/resources/avro_name_sealed_trait_symbol.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroNameSchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/EnumSchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/SealedTraitSchemaTest.scala

This PR addresses an issue referenced in #769
Avro4s wrongfully sorts enum type symbols instead of using in the order they are defined in a schema. AVRO spec states sorting is based on symbol position: https://avro.apache.org/docs/1.11.1/specification/#sort-order
In `AvroNameSchemaTest` there was wrong testdata. `Benelux` had it's subtypes in a different order as in `avro_name_sealed_trait_symbol.json`
The test succeeded because it accidently was sorted in the correct order as `List("foofoo", "Luxembourg").sorted == List("Luxembourg", "foofoo")`, as uppercase chars precede lowercase chars.
To take into account priorities I added `EnumOrdering`, because SubtypeOrdering takes into account the type names.

fix: avro enum sorting by symbol position (as is) not alphabetical

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/unions.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/SealedTraitDecoderTest.scala

PR that potentially solves this [Issue](https://github.com/sksamuel/avro4s/issues/808)

Added annotation to Names while decoding unions

---

project/Build.scala

I ended up with `protobuf-java` 3.7.0 on my project classpath, and found that the culprit was `avro4s-core -> scala3-compiler_3 -> compiler-interface`. The problem is that `protobuf-java` `3.7.0` is very old and has a number of CVEs. 
At any rate, I was confused as to why avro4s needed the `scala3-compiler_3` dependency, so tried compiling without it. It compiles fine, and tests pass.
I assume it was added for a reason, at some point, but maybe is no longer necessary? Or am I missing something?

Remove unnecessary (?) compiler dependency

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroBinaryInputStream.scala

Hey there,
My coworker @maxstreese recently tried backward compatibility using avro4s, but it didn't work out. Here's his code:
```scala
import com.sksamuel.avro4s.*
import java.io.*
@AvroDoc("initial")
@AvroName("Data")
case class Initial(a: Int, b: String)
@AvroDoc("updated")
@AvroName("Data")
case class Updated(a: Int, c: String = "foo")
@main
def main(): Unit =
val buffer = ByteArrayOutputStream()
// producer
val out = AvroOutputStream.binary[Initial].to(buffer).build()
out.write(Initial(1, "x"))
out.close()
// consumer
val in = new AvroBinaryInputStream[Updated](ByteArrayInputStream(buffer.toByteArray), AvroSchema[Initial])
println(in.iterator.next)
```
Clearly this should work because removed fields don't affect backward compatibility and there is a default for the new field `c`. …

use correct reader schema in AvroBinaryInputStream

---

project/Build.scala

Same as https://github.com/sksamuel/avro4s/pull/813. In my case, scala-compiler depends on a version of scala-xml that conflicts with another dependency's version of scala-xml.

Remove scala-compiler dependency for release/4.0.x branch

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/options.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/options.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/OptionDecoderTest.scala

I've added a test that should make it pretty self-explanatory what this PR does

Fix records with `Option` fields with a default that isn't `None`

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/valuetypes.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Annotations.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Names.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/NamespaceSchemaTest.scala

Back in Avro4s 4, case classes inherited the `@Namespace` attribute from their parent trait. This behaviour changed in Avro4s 5, leading to all sorts of incompatible schema changes in our project.
I think the old behaviour was actually more sensible, so this PR restores it.

case class schema derivation: inherit namespace from sealed trait

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/avroutils/SchemaHelper.scala

The current code has this compiler warning:
```
[warn] -- Warning: /code/avro4s/avro4s-core/src/main/scala/com/sksamuel/avro4s/avroutils/SchemaHelper.scala:42:8 
[warn] 42 |        return types.asScala.find(_.getType == Schema.Type.ARRAY).getOrElse {
[warn]    |        ^
[warn]    |Non local returns are no longer supported; use `boundary` and `boundary.break` in `scala.util` instead
```

avoid using 'return'

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroInputStream.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/avroutils/ByteBufferHelper.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/bytes.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/strings.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/bytes.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/strings.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/ByteArrayDecoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/ByteArrayEncoderTest.scala

see #837 
I need to follow up and add some test coverage. This is just an outline of the changes.

support ByteBuffers that have hasArray=false

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Subtypes.scala
avro4s-core/src/test/resources/avro_union_position_enum.json
avro4s-core/src/test/resources/avro_union_position_union.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroSortPrioritySchemaTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroUnionPositionSchemaTest.scala

Seems like annotation `@AvroSortPriority` sorts records in Union in reversed order comparing with Enums, as well as with Enums/Unions from `avro4s:4.x`.
Probably the reason is a sort order [here in Subtypes](https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Subtypes.scala#L17). Comparing with [enums in 5.x](https://github.com/sksamuel/avro4s/blob/2beb8cbdcbb021609bd1b30f922444b81fbc0096/avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/EnumTypes.scala#L14) and [unions in 4.x](https://github.com/sksamuel/avro4s/blob/a4aee30f04eb3f891d5d1e05e91979229dd060ac/avro4s-core/src/main/scala/com/sksamuel/avro4s/TypeUnions.scala#L103), it seems to me that the Ordering compares A with B - ascending order, when instead it should compare B to …

Match Union's sort order with enum's and with sort order in 4.x

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/annotations.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Annotations.scala
avro4s-core/src/test/resources/props_annotation_json_field.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroPropSchemaTest.scala

Avro properties can according to the schema specification and schema api be general json objects, but avro4s currently allows strings. See https://github.com/sksamuel/avro4s/issues/490.

Enable json values for @AvroProp.

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

This is needed to be able to use with frameworks like Apache Flink.
This is similar to circe Encoder and Decoder

Serializable Encoder, Decoder and SchemaFor

---

avro4s-cats/src/main/scala/com/sksamuel/avro4s/cats/package.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/bigdecimals.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/bytes.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/collections.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/eithers.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/options.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/primitives.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/sealedtraits.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/strings.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/temporal.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/tuples.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/encoders/unions.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue387.scala

Hey there,
I'd like to propose to change the return type of `Encoder` from `Any` to `AnyRef`.
The motivation is that some Avro APIs take a parameter of type `Object` (i. e. `AnyRef` in Scala), for example `GenericDatumWriter.write`. The `Any` return type means that in order to use that method I have to add an ugly `.asInstanceOf[AnyRef]`.
Since an `Any` return type is erased to `java.lang.Object` anyway, the return value of `encode` is always an `AnyRef` anyway, so we might as well declare that statically. For the same reason, this should be a binary compatible change.

change return type of `encoder` from `Any` to `AnyRef`

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala

This should make mapped Encoders/Decoders faster because the schema only needs to be processed once, not every time a value is encoded or decoded.

optimize `map` and `contramap`
