sksamuel/avro4s

README.md

Incorrect project name

---

README.md

Handy project! Just wanted this tiny fix for anyone else just pasting the readme snippets into a repl.

Fix README.md walkthrough declaration ordering for REPL sessions

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroOutputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroJsonOutputTest.scala

The library should support json as a way of serialisation.  At the minute only binary and file serialisation is available.

Added Json Support for serialization

---

README.md
avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroInputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroJsonInputTest.scala

The opposite side to the Json serialisation, allows deserialization from Json to a case class

Added Json Support for de-serialization

---

README.md

I have used successfully avro4s. To thank you for your work, I fixed small things in the Readme (lower/upper cases, code format and so on). I bumped dependency indication to 1.4.3 and fixed 2 examples I used.

Changes to Readme

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/MacrosTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/Examples.scala

Added some tests which check referential equality of the generated schema's.
Added data inputstream example code to Examples test.

added macro tests and data stream example

---

avro4s-core/src/test/resources/defaultvalues.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

added handling of int, long, boolean, and double types

handle more default values

---

avro4s-core/src/test/resources/defaultvalues.avsc
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Added support for map and array default values
Added a test for default enum value. A default enum value is mapped to string, which is already supported.

default value support for array, enum, and map

---

README.md
avro4s-core/src/test/scala/com/sksamuel/avro4s/examples/ReadMeExamples.scala

Add corresponding tests for the examples to ensure validity

fix binary serialization example in README

---

README.md

What you asked for. Cheers!
I used SBT's REPL. That is why the namespace is `$iw`. I don't know where that comes from.

finish BigDecimal scale and precision docs

---

avro4s-core/src/test/resources/optiondefaultvalues.avsc
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Related to Incompatible migration with Option #66

Set default to null for Option with default None

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala
project/Build.scala

This PR should fix issues I encondered in https://github.com/sksamuel/avro4s/issues/71. It adds unused import check to compiler and removes imports from macros.

Removed unused imports

---

project/GlobalPlugin.scala

As per title. Hope this helps in getting a release for 2.12 out soon. :pray:

adds scala 2.12 support & 2.11/2.12 cross-compilation settings

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroInputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroBinaryTest.scala

support binary schema evolution

---

avro4s-json/src/main/scala/com/sksamuel/avro4s/json/JsonNamingStrategy.scala
avro4s-json/src/main/scala/com/sksamuel/avro4s/json/JsonToAvroConverter.scala
avro4s-json/src/test/resources/json1_with_lisp_case.json
avro4s-json/src/test/resources/json1_with_pascal_case.json
avro4s-json/src/test/resources/json1_with_snake_case.json
avro4s-json/src/test/resources/json2_with_pascal_case.json
avro4s-json/src/test/scala/com/sksamuel/avro4s/json/JsonToAvroConverterTest.scala

add support for json convertion with different naming convention

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroInputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroInputStreamBuilderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/VersioningTest.scala

My proposition for solving issue described in ticket: https://github.com/sksamuel/avro4s/issues/130

Using different schema for reading and writing

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroInputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroOutputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/ToRecordTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/UniverseTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

The change will break the compatibility with message produced with the current conversion.
Not sure how to document it, any idea?

#127 - use decimal conversion for big decimal

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala
avro4s-macros/src/test/scala/com/sksamuel/avro4s/macros/BigDecimalToValueTest.scala

Pull request related to https://github.com/sksamuel/avro4s/issues/141

Setting scale for BigDecimal value in 'BigDecimalToValue' apply method

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

support overriding record namespace per field

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala
version.sbt

I think this will fix the issues mentioned in https://github.com/sksamuel/avro4s/issues/19#issuecomment-385678804 and https://github.com/sksamuel/avro4s/issues/223

ToValue and LowPriorityToValue extends Serializable

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala

Wow! Thanks for taking the time to do this.  There is a team of people that really appreciate it :)

fix Option TraitObjectEnum not serializing

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/Encoder.scala
project/GlobalPlugin.scala

Restore scala 2.11 compatibility.

---

avro4s-macros/src/main/scala/com/sksamuel/avro4s/Decoder.scala

Use Scala reflection to get instance of enum rather than Java

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/FromRecord.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/RecordFormat.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/Github284.scala

Applied suggested change by update the parameter type from GenericRecord to IndexedRecord, in order to handle conversion between a specific record and case class

RecordFormat.from accepts IndexRecord

---

avro4s-core/src/test/resources/record_option_record_adt.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/RecordOptionRecordAdt.scala
avro4s-macros/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala

Fixes [#334](https://github.com/sksamuel/avro4s/issues/334).
One test (that was to fail before fix) added.

Fixed #334 schema macro

---

README.md
avro4s-cats/src/main/scala/com/sksamuel/avro4s/cats/package.scala
avro4s-refined/src/main/scala/com/sksamuel/avro4s/refined/package.scala
avro4s-refined/src/test/scala/com/sksamuel/avro4s/refined/RefinedTest.scala
build.sbt
project/Build.scala

Closes #327 
Let me know if I should comment out the `avro4s-refined` sbt module like the cats one is, or if you'd like the cats one uncommented (if the only thing missing for the cats one is tests I'd be happy to add those to this PR).

Adds refined module

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AnnotationExtractors.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaFor.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/annotations.scala
avro4s-core/src/test/resources/avro_sort_priority_enum.json
avro4s-core/src/test/resources/avro_sort_priority_union.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroSortPrioritySchemaTest.scala

This is one way of fixing #343

Add an @AvroSortPriority annotation

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Encoder.scala
avro4s-core/src/test/resources/recursive_coproduct.json
avro4s-core/src/test/resources/recursive_list.json
avro4s-core/src/test/resources/recursive_map.json
avro4s-core/src/test/resources/recursive_option.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/Recursive.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/RecursiveEncoderTest.scala

Add recursive encoder tests

---

README.md

Document withSchema and recursive types in README

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/ImmutableRecord.scala

Improvement suggestion based on #392 and #385
@sksamuel, @yeryomenkom wdyt?

Pre-compute field name indices to reduce access time in ImmutableRecord.get

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SafeFrom.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue484.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue485.scala

Fix serialization issues with coproduct and scala enum decoders

---

avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue432.scala
project/Build.scala

context: https://github.com/scala/community-build/pull/1172

upgrade ScalaTest to version 3.2.0

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultAvroOutputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue510.scala

Make AvroOutputStream.binary support primitive types

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/CollectionsAndContainers.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/OptionEncoderTest.scala

Properly deconstruct option schema

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/AvroDataInputStream.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/streams/input/BasicInputStreamTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/streams/input/InputStreamTest.scala

Fix error handling of AvroDataInputStream

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Records.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/ReorderFieldsDecoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/ReorderFieldsEncoderTest.scala

Honor custom field encoding

---

avro4s-kafka/src/main/scala/com/sksamuel/avro4s/kafka/GenericSerde.scala
avro4s-kafka/src/test/scala/com/sksamuel/avro4s/kafka/GenericSerdeTest.scala

Consider tombstones in GenericSerde.serialize

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/Temporals.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/DateDecoderTest.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/DateEncoderTest.scala

Fixes #549 
Also adding logical type support for timestamp

Add Instant logical type support

---

.github/stale.yml

Make stale bot use "abandoned" instead of "wontfix"

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/annotations.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/avroutils/SchemaHelper.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Annotations.scala
avro4s-core/src/test/resources/avro_error.json
avro4s-core/src/test/resources/avro_error_field.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/AvroErrorSchemaTest.scala

Added support for error records through @AvroError

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/CustomDefaults.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/Records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/SchemaHelper.scala
avro4s-core/src/test/resources/case_class_list_multiple_default_values.json
avro4s-core/src/test/resources/case_class_list_single_default_values.json
avro4s-core/src/test/resources/case_class_set_multiple_default_values.json
avro4s-core/src/test/resources/case_class_set_single_default_values.json
avro4s-core/src/test/resources/case_object_list_multiple_default_values.json
avro4s-core/src/test/resources/case_object_list_single_default_values.json
avro4s-core/src/test/resources/case_object_set_multiple_default_values.json
avro4s-core/src/test/resources/case_object_set_single_default_values.json
avro4s-core/src/test/resources/default_values_optional_enum_list_multiple.json
avro4s-core/src/test/resources/default_values_optional_enum_list_none.json
avro4s-core/src/test/resources/default_values_optional_enum_list_single.json
avro4s-core/src/test/resources/default_values_optional_enum_set_multiple.json
avro4s-core/src/test/resources/default_values_optional_enum_set_none.json
avro4s-core/src/test/resources/default_values_optional_enum_set_single.json
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala

Addresses https://github.com/sksamuel/avro4s/issues/677
Including various use-cases: collections and sets, optional collections and sets, unions and enums

Support array default values

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/decoders/sealedtraits.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/record/decoder/SealedTraitDecoderTest.scala

Added a test for this case.
Also updated the other tests in `SealedTraitDecoderTest` so they now compile, but they are all failing so I've left them commented out.

Support decoding of sealed trait + case object enums

---

avro4s-core/src/main/scala/com/sksamuel/avro4s/CustomDefaults.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/DefaultResolver.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/avroutils/SchemaHelper.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/schemas/records.scala
avro4s-core/src/main/scala/com/sksamuel/avro4s/typeutils/Annotations.scala
avro4s-core/src/test/scala/com/sksamuel/avro4s/schema/DefaultValueSchemaTest.scala
project/Build.scala

This reintroduces part of the default values.
I did not reintroduce the custom types because I'm not sure if this is the right thing to do. I needs more discussion is a follow up PR IMO. But in the meantime we need this to unlock some work on our side.

Reintroduce defaults

---

project/plugins.sbt

Revert "Update sbt-pgp to 2.3.0"

---

project/plugins.sbt

Revert "Revert "Update sbt-pgp to 2.3.0""
